/**
 * songs.js
 *
 * The app's songs
 */

window.songs = [
  /* TODO */
  {
    songId: "ID-1",
    artistId: "AID-1",
    image:
      "https://i.discogs.com/jn-KSHVkJj4PoJ7aNwH6W4vNDHTGBoFZP7aOr4OHKCg/rs:fit/g:sm/q:90/h:500/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyNzUz/MDcwLTE2NDkwMTQ1/MzEtNTM5Ny5qcGVn.jpeg",
    title: "Faded",
    year: "2015",
    duration: 196,
    url: "https://www.youtube.com/watch?v=60ItHLz5WEA",
    explicit: false,
  },
  {
    songId: "ID-2",
    artistId: "AID-1",
    image:
      "https://i1.sndcdn.com/artworks-7r44yOh7LqBpo0QZ-yMOb9Q-t500x500.jpg",
    title: "Lost",
    year: "2018",
    duration: 296,
    url: "https://www.youtube.com/watch?v=gRC30wQG79A",
    explicit: false,
  },
  {
    songId: "ID-3",
    artistId: "AID-1",
    image:
      "https://i1.sndcdn.com/artworks-o1ySVNteRW1IDshO-gPuSgw-t500x500.jpg",
    title: "Headlights",
    year: "2022",
    duration: 150,
    url: "https://youtu.be/kyLuzKbgXAs?si=knCuu6DmFGp7xWIu",
    explicit: false,
  },
  {
    songId: "ID-4",
    artistId: "AID-1",
    image:
      "https://upload.wikimedia.org/wikipedia/en/c/c3/Alan_Walker_The_Spectre.jpg",
    title: "Spectre",
    year: "2021",
    duration: 210,
    url: "https://www.youtube.com/watch?v=wJnBTPUQS5A",
    explicit: false,
  },
  {
    songId: "ID-5",
    artistId: "AID-1",
    image:
      "https://d1nxzqpcg2bym0.cloudfront.net/google_play/com.alanwalker.darkside/3ee6e9aa-9e59-11e8-8ef5-13b12e14f24d/640",
    title: "Darkside",
    year: "2018",
    duration: 170,
    url: "https://youtu.be/kyLuzKbgXAs?si=WyfM7gJV85RSo1Hb",
    explicit: false,
  },
  {
    songId: "ID-6",
    artistId: "AID-1",
    image:
      "https://i1.sndcdn.com/artworks-jXgAJLAugg2hDdE6-oN3cYA-t500x500.jpg",
    title: "Alone",
    year: "2016",
    duration: 165,
    url: "https://www.youtube.com/watch?v=1-xGerv5FOk",
    explicit: false,
  },
  {
    songId: "ID-7",
    artistId: "AID-1",
    title: "Sing Me to sleep",
    image:
      "https://i1.sndcdn.com/artworks-HdqDNwrWsWViuyv8-EM91HQ-t500x500.jpg",
    year: "2016",
    duration: 200,
    url: "https://www.youtube.com/watch?v=2i2khp_npdE",
    explicit: false,
  },
  {
    songId: "ID-8",
    artistId: "AID-2",
    title: "Rolling in the deep",
    image: "https://i1.sndcdn.com/artworks-000102426886-jjbupk-t500x500.jpg",
    year: "2010",
    duration: 230,
    url: "https://www.youtube.com/watch?v=rYEDA3JcQqw",
    explicit: false,
  },
  {
    songId: "ID-9",
    artistId: "AID-2",
    title: "Set Fire to the rain",
    image: "https://i.ytimg.com/vi/JJKk5IPkH6E/maxresdefault.jpg",
    year: "2011",
    duration: 237,
    url: "https://youtu.be/Ri7-vnrJD3k?si=0Eu89rqDLisILfWC",
    explicit: false,
  },
  {
    songId: "ID-10",
    artistId: "AID-2",
    title: "Skyfall",
    image:
      "https://upload.wikimedia.org/wikipedia/en/6/6b/Skyfall_-_Original_Motion_Picture_Soundtrack.jpg",
    year: "2012",
    duration: 290,
    url: "https://www.youtube.com/watch?v=DeumyOzKqgI",
    explicit: false,
  },
  {
    songId: "ID-11",
    artistId: "AID-2",
    title: "Hello",
    image: "https://i1.sndcdn.com/artworks-000296903232-wbms8b-t500x500.jpg",
    year: "2015",
    duration: 370,
    url: "https://www.youtube.com/watch?v=YQHsXMglC9A",
    explicit: false,
  },
  {
    songId: "ID-12",
    artistId: "AID-2",
    title: "Someone Like you",
    image: "https://live.staticflickr.com/6209/6133388851_6e208cdd44_b.jpg",
    year: "2011",
    duration: 283,
    url: "https://youtu.be/hLQl3WQQoQ0?si=R1vcXk_2PbieWL6o",
    explicit: false,
  },
  {
    songId: "ID-13",
    artistId: "AID-2",
    title: "I drink wine",
    image: "https://i.ytimg.com/vi/axUh_2fTLe4/maxresdefault.jpg",
    year: "2022",
    duration: 420,
    url: "https://www.youtube.com/watch?v=jDvYDzFOK9A",
    explicit: false,
  },
  {
    songId: "ID-14",
    artistId: "AID-2",
    image:
      "https://m.media-amazon.com/images/M/MV5BODU5OGI5ZGQtODk2OS00ZDljLThjNzctNWQ5NmY4YzliMDU4XkEyXkFqcGdeQXVyNDE4OTY5NzI@._V1_.jpg",
    title: "Send me my love",
    year: "2016",
    duration: 225,
    url: "https://www.youtube.com/watch?v=fk4BbF7B29w",
    explicit: false,
  },
  {
    songId: "ID-15",
    artistId: "AID-3",
    image: "https://i1.sndcdn.com/artworks-000344148633-qrms3b-t500x500.jpg",
    title: "Alone",
    year: "2016",
    duration: 200,
    url: "https://www.youtube.com/watch?v=ALZHF5UqnU4",
    explicit: false,
  },
  {
    songId: "ID-16",
    artistId: "AID-3",
    image:
      "https://upload.wikimedia.org/wikipedia/en/e/ed/Moving_On_Marshmello.jpg",
    title: "Moving On",
    year: "2017",
    duration: 180,
    url: "https://www.youtube.com/watch?v=yU0tnrEk8H4",
    explicit: false,
  },
  {
    songId: "ID-17",
    artistId: "AID-3",
    image:
      "https://upload.wikimedia.org/wikipedia/en/e/e5/Marshmello_and_Bastille_Happier.png",
    title: "Happier",
    year: "2018",
    duration: 235,
    url: "https://www.youtube.com/watch?v=m7Bc3pLyij0",
    explicit: false,
  },
  {
    songId: "ID-18",
    artistId: "AID-3",
    image: "https://i1.sndcdn.com/artworks-000363751398-91dvqy-t1080x1080.jpg",
    title: "Together",
    year: "2018",
    duration: 230,
    url: "https://www.youtube.com/watch?v=JePnQ1gSagc",
    explicit: false,
  },
  {
    songId: "ID-19",
    artistId: "AID-3",
    title: "Friends",
    image:
      "https://cdns-images.dzcdn.net/images/cover/b57e2db906a8af3c54b4485313bf18c2/1900x1900-000000-80-0-0.jpg",
    year: "2018",
    duration: 231,
    url: "https://www.youtube.com/watch?v=jzD_yyEcp0M",
    explicit: false,
  },
  {
    songId: "ID-20",
    artistId: "AID-3",
    image: "https://i.ytimg.com/vi/Ubwzz8Qne0E/maxresdefault.jpg",
    title: "Stars",
    year: "2018",
    duration: 210,
    url: "https://www.youtube.com/watch?v=A57B7B6w3kw",
    explicit: false,
  },
  {
    songId: "ID-21",
    artistId: "AID-3",
    title: "Blocks",
    image: "https://i1.sndcdn.com/artworks-000109237803-qk1y1g-t500x500.jpg",
    year: "2017",
    duration: 207,
    url: "https://www.youtube.com/watch?v=5E4ZBSInqUU",
    explicit: false,
  },
  {
    songId: "ID-22",
    artistId: "AID-1",
    image: "https://pbs.twimg.com/media/FE1FhWHWUAEXfQK.jpg:large",
    title: "Belki",
    year: "2022",
    duration: 210,
    url: "https://www.youtube.com/watch?v=7-_qRtGbCTE",
    explicit: true,
  },
  {
    songId: "ID-23",
    artistId: "AID-1",
    image: "https://pbs.twimg.com/media/FE1FhWHWUAEXfQK.jpg:large",
    title: "Dont Copy My flow",
    year: "2024",
    duration: 300,
    url: "https://www.youtube.com/watch?v=8qEtaUOd0aE",
    explicit: true,
  },
];
